#!/bin/sh
set -e


# Get the list of changed YAML files
changed_yaml_files=$(git diff --cached --name-only --diff-filter=ACMRTUXB ./**/*.yml)

# Run yamllint only on the changed YAML files
if [ -n "$changed_yaml_files" ]; then
  echo "Running pre-commit yamllint checks..."
  yamllint -c .yamllint $changed_yaml_files

  echo "Generating SERVICES.md..."
  # Call the script to generate SERVICES.md
  .githooks/generate-services-markdown.sh

  # Add SERVICES.md to the commit
  git add ./SERVICES.md
fi