FROM rust:1.75 as builder
WORKDIR /usr/src/autokuma
RUN cargo install --git https://github.com/BigBoot/AutoKuma.git kuma-cli
RUN cargo install --git https://github.com/BigBoot/AutoKuma.git autokuma

 
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl3 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/* /usr/local/bin
CMD ["autokuma"]