networks:
  traefik:
    external: true

# config_version: 2
# description: Web-based user interface for ollama LLM and others
# https://github.com/open-webui/open-webui

services:
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:${OLLAMA_WEBUI_DOCKER_TAG:-main}
    env_file:
      - ./services-enabled/ollama-webui.env
    container_name: ${OLLAMA_WEBUI_CONTAINER_NAME:-ollama-webui}
    restart: ${OLLAMA_WEBUI_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ./etc/ollama-webui:/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENABLE_OPENAI_API=true
      - OPENAI_API_BASE_URLS=http://pipelines:9099
      - OPENAI_API_KEYS=${PIPELINES_API_KEY}
      - CONTENT_EXTRACTION_ENGINE=docling
      - DOCLING_SERVER_URL=http://docling-serve:5001
      - DOCLING_PARAMS={"force_ocr":true,"do_ocr":true,"ocr_lang":["en"]}
      - BYPASS_EMBEDDING_AND_RETRIEVAL=true
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - WEB_SEARCH_RESULT_COUNT=${OLLAMA_WEBUI_WEB_SEARCH_RESULT_COUNT:-3}
      - WEB_SEARCH_CONCURRENT_REQUESTS=${OLLAMA_WEBUI_WEB_SEARCH_CONCURRENT_REQUESTS:-10}
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
    labels:
      - joyride.host.name=${OLLAMA_WEBUI_HOST_NAME:-chat}.${HOST_DOMAIN}
      - traefik.enable=${OLLAMA_WEBUI_TRAEFIK_ENABLE:-true}
      - traefik.http.routers.ollama-webui.entrypoints=websecure
      - traefik.http.routers.ollama-webui.rule=Host(`${OLLAMA_WEBUI_HOST_NAME:-chat}.${HOST_DOMAIN}`)
      - traefik.http.services.ollama-webui.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=${OLLAMA_WEBUI_WATCHTOWER_ENABLE:-true}
      - autoheal=${OLLAMA_WEBUI_AUTOHEAL:-false}
