#!/usr/bin/env python
"""Generate and migrate Proxmox external instance Traefik config."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

GENERATED_HEADER = "# Generated by OnRamp; edit services-enabled/proxmox.external.yml instead\n"
SOURCE_MANAGED_BY = "onramp-migration"
SUPPORTED_MESSAGE = "external instance generation is currently supported for: proxmox"
KEY_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
DNS_LABEL_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")
ADDRESS_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9.-]*$")
DOTENV_RE = re.compile(r"^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


class ExternalInstancesError(RuntimeError):
    """Raised for actionable external instance validation errors."""


@dataclass(frozen=True)
class ServiceProfile:
    """Internal service render profile."""

    name: str
    port: int
    entrypoints: list[str]
    middlewares: list[str]


PROFILES: dict[str, ServiceProfile] = {
    "proxmox": ServiceProfile(
        name="proxmox",
        port=8006,
        entrypoints=["websecure"],
        middlewares=["default-headers"],
    )
}


def _profile(service: str) -> ServiceProfile:
    if service not in PROFILES:
        raise ExternalInstancesError(SUPPORTED_MESSAGE)
    return PROFILES[service]


def _repo_root_from_sietch() -> Path:
    return Path(__file__).resolve().parents[2]


def _contains_unsafe(value: str) -> bool:
    return any(token in value for token in ("`", "{{", "}}", "\n", "\r", "\t"))


def _validate_dns_name(value: str, field: str) -> str:
    value = str(value).strip().lower()
    if not value or value.endswith(".") or "*" in value or _contains_unsafe(value):
        raise ExternalInstancesError(f"invalid {field}: {value!r}")
    labels = value.split(".")
    if any(not DNS_LABEL_RE.fullmatch(label) for label in labels):
        raise ExternalInstancesError(f"invalid {field}: {value!r}")
    return value


def _validate_address(value: str) -> str:
    value = str(value).strip()
    if (
        not value
        or "://" in value
        or "/" in value
        or ":" in value
        or value.endswith(".")
        or _contains_unsafe(value)
        or not ADDRESS_RE.fullmatch(value)
    ):
        raise ExternalInstancesError(f"invalid address: {value!r}")
    return value


def _load_yaml(path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ExternalInstancesError(f"malformed YAML in {path}: {exc}") from exc
    except OSError as exc:
        raise ExternalInstancesError(f"could not read {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ExternalInstancesError(f"{path} must contain a YAML mapping")
    return data


def _dump_yaml(data: dict[str, Any]) -> str:
    return yaml.safe_dump(data, sort_keys=False, default_flow_style=False).replace("\r\n", "\n")


def read_dotenv(path: Path) -> dict[str, str]:
    """Read a strict dotenv file without mutating process environment."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = DOTENV_RE.fullmatch(line)
        if not match:
            raise ExternalInstancesError(f"unsupported dotenv syntax in {path}:{line_number}")
        key, value = match.groups()
        if key in values:
            raise ExternalInstancesError(f"duplicate dotenv key {key} in {path}:{line_number}")
        if " #" in value or "\t#" in value:
            raise ExternalInstancesError(f"inline comments are not supported in {path}:{line_number}")
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        values[key] = value
    return values


def _domain_from_env(base_dir: Path) -> str | None:
    services = base_dir / "services-enabled"
    merged: dict[str, str] = {}
    for name in (".env", ".env.external"):
        for key, value in read_dotenv(services / name).items():
            merged.setdefault(key, value)
    domain = merged.get("HOST_DOMAIN")
    return _validate_dns_name(domain, "domain") if domain else None


def _normalize_instances(data: dict[str, Any], default_domain: str | None) -> dict[str, dict[str, str]]:
    raw_instances = data.get("instances")
    if not isinstance(raw_instances, dict) or not raw_instances:
        raise ExternalInstancesError("instances must be a non-empty mapping")
    normalized: dict[str, dict[str, str]] = {}
    fqdns: set[str] = set()
    for key in sorted(raw_instances):
        if not KEY_RE.fullmatch(str(key)):
            raise ExternalInstancesError(f"invalid instance key: {key!r}")
        raw = raw_instances[key]
        if not isinstance(raw, dict):
            raise ExternalInstancesError(f"instance {key} must be a mapping")
        address = raw.get("address")
        if not address:
            raise ExternalInstancesError(f"instance {key} missing address")
        instance: dict[str, str] = {"address": _validate_address(str(address))}
        if raw.get("fqdn"):
            fqdn = _validate_dns_name(str(raw["fqdn"]), "fqdn")
            instance["fqdn"] = fqdn
        else:
            host_name = raw.get("host_name")
            if not host_name:
                raise ExternalInstancesError(f"instance {key} missing host_name")
            domain = raw.get("domain") or default_domain
            if not domain:
                raise ExternalInstancesError(
                    "domain is required: set instance domain/fqdn or HOST_DOMAIN"
                )
            instance["host_name"] = _validate_dns_name(str(host_name), "host_name")
            instance["domain"] = _validate_dns_name(str(domain), "domain")
            fqdn = f"{instance['host_name']}.{instance['domain']}"
        if fqdn in fqdns:
            raise ExternalInstancesError(f"duplicate FQDN: {fqdn}")
        fqdns.add(fqdn)
        instance["_fqdn"] = fqdn
        normalized[str(key)] = instance
    return normalized


def render_traefik(service: str, source: dict[str, Any], default_domain: str | None) -> str:
    """Render deterministic Traefik YAML for a supported service."""
    profile = _profile(service)
    instances = _normalize_instances(source, default_domain)
    routers: dict[str, Any] = {}
    services: dict[str, Any] = {}
    for key, instance in instances.items():
        router_name = key
        service_name = key
        routers[router_name] = {
            "rule": f"Host(`{instance['_fqdn']}`)",
            "entrypoints": profile.entrypoints,
            "middlewares": profile.middlewares,
            "tls": {},
            "service": service_name,
        }
        services[service_name] = {
            "loadBalancer": {
                "passHostHeader": True,
                "servers": [{"url": f"https://{instance['address']}:{profile.port}/"}],
            }
        }
    return GENERATED_HEADER + _dump_yaml({"http": {"routers": routers, "services": services}})


def _backup(path: Path) -> Path:
    backup = path.with_name(f"{path.name}.bak")
    index = 1
    while backup.exists():
        backup = path.with_name(f"{path.name}.bak{index}")
        index += 1
    shutil.copy2(path, backup)
    return backup


def _write_active(path: Path, content: str, *, dry_run: bool, force: bool, replace_unmanaged: bool) -> str:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == content:
            return "active config is up to date"
        if not current.startswith(GENERATED_HEADER):
            if not replace_unmanaged:
                raise ExternalInstancesError("refusing to overwrite unmanaged active config")
            if dry_run:
                return "would backup and replace unmanaged active config"
            backup = _backup(path)
            action = f"backed up unmanaged active config to {backup} and replaced it"
        elif not force and not dry_run:
            action = "updated generated active config"
        else:
            action = "updated generated active config"
    else:
        action = "created generated active config"
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return action


def generate(service: str, base_dir: Path, *, dry_run: bool, force: bool, replace_unmanaged: bool) -> str:
    _profile(service)
    source_path = base_dir / "services-enabled" / f"{service}.external.yml"
    target_path = base_dir / "external-enabled" / f"{service}.yml"
    if not source_path.exists():
        raise ExternalInstancesError(f"missing source config: {source_path}")
    rendered = render_traefik(service, _load_yaml(source_path), _domain_from_env(base_dir))
    action = _write_active(target_path, rendered, dry_run=dry_run, force=force, replace_unmanaged=replace_unmanaged)
    return f"{action}\n{rendered if dry_run else ''}".rstrip() + "\n"


def _legacy_instances(base_dir: Path) -> tuple[dict[str, dict[str, str]], str | None]:
    services = base_dir / "services-enabled"
    env = read_dotenv(services / ".env")
    env.update(read_dotenv(services / ".env.external"))
    domain = env.get("HOST_DOMAIN")
    instances: dict[str, dict[str, str]] = {}
    for suffix, key in [("", "proxmox"), *[(str(i), f"proxmox{i}") for i in range(2, 11)]]:
        prefix = f"PROXMOX{suffix}_"
        host = env.get(f"{prefix}HOST_NAME")
        address = env.get(f"{prefix}ADDRESS")
        if bool(host) ^ bool(address):
            raise ExternalInstancesError(f"incomplete legacy Proxmox pair for {prefix.rstrip('_')}")
        if host and address:
            instances[key] = {"host_name": host, "address": address}
    if not instances:
        raise ExternalInstancesError("no legacy Proxmox env vars found")
    return instances, domain


def _source_content(instances: dict[str, dict[str, str]]) -> str:
    return _dump_yaml({"managed_by": SOURCE_MANAGED_BY, "instances": instances})


def migrate(service: str, base_dir: Path, *, dry_run: bool, force: bool, replace_unmanaged: bool) -> str:
    _profile(service)
    migrated, domain = _legacy_instances(base_dir)
    source_path = base_dir / "services-enabled" / f"{service}.external.yml"
    if source_path.exists():
        existing = _load_yaml(source_path)
        if existing.get("managed_by") != SOURCE_MANAGED_BY:
            if not replace_unmanaged:
                raise ExternalInstancesError("refusing to overwrite unmanaged source config")
            if not dry_run:
                backup = _backup(source_path)
            existing = {"managed_by": SOURCE_MANAGED_BY, "instances": {}}
            backup_msg = f"backed up unmanaged source config to {backup}; " if not dry_run else "would backup unmanaged source config; "
        else:
            backup_msg = ""
        merged = dict(existing.get("instances") or {})
        for key, value in migrated.items():
            old = merged.get(key)
            if isinstance(old, dict) and old != value and not force:
                raise ExternalInstancesError(f"managed source conflict for instance {key}; use --force to update")
            merged[key] = value
        data = {"managed_by": SOURCE_MANAGED_BY, "instances": dict(sorted(merged.items()))}
    else:
        backup_msg = ""
        data = {"managed_by": SOURCE_MANAGED_BY, "instances": dict(sorted(migrated.items()))}
    _normalize_instances(data, _validate_dns_name(domain, "domain") if domain else None)
    content = _source_content(data["instances"])
    if source_path.exists() and source_path.read_text(encoding="utf-8") == content:
        return "source config is up to date\n"
    if not dry_run:
        source_path.parent.mkdir(parents=True, exist_ok=True)
        source_path.write_text(content, encoding="utf-8", newline="\n")
    return f"{backup_msg}{'would write' if dry_run else 'wrote'} source config\n{content if dry_run else ''}".rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("generate", "migrate"):
        sub = subparsers.add_parser(command)
        sub.add_argument("service")
        sub.add_argument("--base-dir", type=Path, default=_repo_root_from_sietch())
        sub.add_argument("--dry-run", action="store_true")
        sub.add_argument("--force", action="store_true")
        sub.add_argument("--replace-unmanaged", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.command == "generate":
            output = generate(args.service, args.base_dir, dry_run=args.dry_run, force=args.force, replace_unmanaged=args.replace_unmanaged)
        else:
            output = migrate(args.service, args.base_dir, dry_run=args.dry_run, force=args.force, replace_unmanaged=args.replace_unmanaged)
    except ExternalInstancesError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
